version: '3.8'

services:
  jmeter-master:
    image: justb4/jmeter:5.6.3
    container_name: jmeter-performance
    volumes:
      - ./test-plans:/test-plans
      - ./results:/results
      - ./config:/config
    command: >
      /bin/sh -c "
      jmeter -n -t /test-plans/api-performance.jmx
      -p /config/test.properties
      -l /results/results.jtl
      -e -o /results/html-report
      -Jthreads=50 -Jrampup=120
      && sh /config/check-thresholds.sh /results/results.jtl
      "