version: '3.8'

services:
  jmeter-master:
    image: justb4/jmeter:latest
    container_name: jmeter-performance
    volumes:
      - ./test-plans:/test-plans
      - ./results:/results
      - ./config:/config