version: '3.8'

services:
  jmeter-master:
    image: justb4/jmeter:latest
    container_name: jmeter-performance
    user: "0"
    volumes:
      - ${PWD}/test-plans:/test-plans
      - ${PWD}/results:/results
      - ${PWD}/config:/config
    command: >
      -n -t /test-plans/api-performance.jmx
      -l /results/results.jtl
      -e -o /results/html-report
      -Jthreads=50
      -Jrampup=120
      -Jbase.url=httpbin.org